name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and calculate score
      run: |
        pytest --junitxml=results.xml
        python calculate_score.py results.xml  # Provide the file name here

    - name: Save score
      id: save_score
      run: echo "SCORE=$(python calculate_score.py results.xml)" >> $GITHUB_ENV

    - name: Print score
      run: echo "The calculated score is ${{ env.SCORE }}"
